[build]
  command = "npm run build"
  publish = "client/.next"

[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3001/api/:splat"
  status = 200
  force = true

[context.production.environment]
  NEXT_PUBLIC_APP_URL = "https://your-app.netlify.app"