services:
  # Frontend
  - type: web
    name: securecontract-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false

  # Backend
  - type: web
    name: securecontract-backend
    env: node
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVER_PORT
        value: 3001
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false